config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: 'posts#index'
end

app/models/parser.rb
class Parser < ActiveRecord::Base

  require 'open-uri'
  require 'nokogiri'

  default_scope { order(created_at: :desc) }

  def self.parser
    data = []
    source = 'https://habrahabr.ru/'
    agent = 'firefox'

    page = Nokogiri::HTML(open(source, 'User-Agent' => agent))

    page.css('h1.title a.post_title').each do |link|
      data << [link['href'], link.children.text]
    end

    data.reverse_each do |value|
      result = Parser.where(url: value.first)

      if result.blank?
        Parser.create(title: value.last, url: value.first)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :habr_parser, only: [:index]

  def index
    @posts = Parser.all.take(10)

  end

  private

  def habr_parser
    Parser.delay.parser
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Обновить', posts_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Parser Demo'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Parser Demo'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/posts/index.html.haml
.well
  %h2 Последние #{@posts.count} статей из хабра:
  - @posts.each do |habr|
    %h3
      = link_to habr.title, habr.url